version: "3.8"

services:
 fluentd:
   image: fluent/fluentd:v1.16-2
   user: root
   volumes:
     - "./fluentd/conf:/fluentd/etc"
     - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
     - "/var/run/docker.sock:/var/run/docker.sock:ro"
   networks:
      - "glpi-network"
   #command: ["--environment", "container"]
   restart: on-failure
networks:
  glpi-network:
    external: true