version: "3.8"

services:
 fluentd:
   #image: fluent/fluentd:v1.16-2
   build: ./fluentd
   user: root
   volumes:
     - "./fluentd/conf:/fluentd/etc"
     - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
     - "/var/run/docker.sock:/var/run/docker.sock:ro"
   networks:
      - "glpi-network"
   restart: on-failure
   ports:
     - "24224:24224"
     - "24224:24224/udp"
networks:
  glpi-network:
    external: true